### ISSUE TITLE
Mexico Tool Kit still functional after trump installation

### ISSUE THREAD

**Issue by njburgoyne** [romainfrancois/trump#3]
Expected this to be blocked in some way:

https://cran.r-project.org/web/packages/mtk/index.html

...broken promises ;)

**Comment by romainfrancois** [comment]
Could have something like this: 

```r
if( "mtk" %in% rownames(installed.packages())){
      remove.packages( "mtk" )
}
```

**Comment by njburgoyne** [comment]
...thank goodness that won't be possible for the **foreign**(ers) package!

**Comment by romainfrancois** [comment]
```
remove.packages( "obamacare") 
```

might happen though
